"""and

Revision ID: 7c1d239cd216
Revises: e31377494279
Create Date: 2025-07-05 20:54:24.640667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c1d239cd216'
down_revision = 'e31377494279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_unique_constraint('_sno_cno_uc', ['sno', 'cno'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_constraint('_sno_cno_uc', type_='unique')

    # ### end Alembic commands ###
