"""Initial migration.

Revision ID: dc40eab7a806
Revises: 
Create Date: 2025-07-03 18:15:55.866888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc40eab7a806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('cno', sa.String(length=20), nullable=False),
    sa.Column('cname', sa.String(length=50), nullable=False),
    sa.Column('cpno', sa.String(length=20), nullable=True),
    sa.Column('ccredit', sa.Integer(), nullable=False),
    sa.Column('cteacher', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cpno'], ['courses.cno'], ),
    sa.PrimaryKeyConstraint('cno')
    )
    op.create_table('students',
    sa.Column('sno', sa.String(length=20), nullable=False),
    sa.Column('sname', sa.String(length=50), nullable=False),
    sa.Column('ssex', sa.String(length=2), nullable=False),
    sa.Column('sage', sa.Integer(), nullable=False),
    sa.Column('sdept', sa.String(length=50), nullable=False),
    sa.Column('hometown', sa.String(length=50), nullable=False),
    sa.CheckConstraint("ssex IN ('男', '女')", name='ssex_check'),
    sa.CheckConstraint('sage > 0 AND sage < 100', name='sage_check'),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('score',
    sa.Column('sno', sa.String(length=20), nullable=False),
    sa.Column('cno', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cno'], ['courses.cno'], ),
    sa.ForeignKeyConstraint(['sno'], ['students.sno'], ),
    sa.PrimaryKeyConstraint('sno', 'cno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('courses')
    # ### end Alembic commands ###
