"""s.

Revision ID: e31377494279
Revises: dc40eab7a806
Create Date: 2025-07-03 19:31:06.818813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31377494279'
down_revision = 'dc40eab7a806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
